[tool.poetry]
name = "pho-jupyter-preview-widget"
version = "0.1.0"
description = ""
authors = ["Pho Hale <PhoHale@gmail.com>"]
readme = "README.md"
include = [
    { path = "pho_jupyter_preview_widget/static/js/widget.js", format = ["sdist", "wheel"]  }
]

[tool.poetry.dependencies]
python = "^3.9"
ipywidgets = "^8.1.3"
ipykernel = "^6.29.5"
pandas = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
notebook = ["notebook"]

[tool.poetry.scripts]

